angular.module("arkano_angular")
    .config([
        "$locationProvider",
        "$stateProvider",
        "$urlRouterProvider",
        "$httpProvider",
        function($locationProvider,$stateProvider,$urlRouterProvider,$httpProvider){
            $locationProvider.hashPrefix("!").html5Mode(true);
            $stateProvider
                .state("Home",{
                    url:"/",
                    templateUrl:"app/src/home/home.tpl.html",
                    controller:"homeCtrl",
                    controllerAs:"home"
                })
                .state("Authorize",{
                    url:"/authorize",
                    templateUrl:"app/src/authorize/authorize.tpl.html",
                    controller:"authorizeCtrl",
                    controllerAs:"authorize"
                });
            //$httpProvider.interceptors.push('AuthInterceptor');
        }
    ])
    .run([
        function(){
            
        }
    ]);